# Generated by Django 5.1.6 on 2024-12-01 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_interest_date_created_investment_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='date_created',
        ),
    ]
