# Generated by Django 4.2.27 on 2026-06-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestformpayment',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
