# Generated by Django 5.1.6 on 2025-09-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayback',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
