# Generated by Django 5.1.6 on 2025-09-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequestfee',
            name='loan_amount',
        ),
        migrations.AddField(
            model_name='loanrequestfee',
            name='loan_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.loantype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loantype',
            name='request_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
