# Generated by Django 4.2.27 on 2026-04-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='account_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
