# Generated by Django 5.1.6 on 2025-08-16 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_unit'),
        ('loan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loanrequest',
            constraint=models.CheckConstraint(condition=models.Q(('approved_amount__lte', models.F('amount'))), name='approved_amount_not_greater_than_requested'),
        ),
    ]
