# Generated by Django 5.1.6 on 2025-11-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayback',
            name='loan_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='loan_receipts'),
        ),
    ]
