# Generated by Django 5.1.6 on 2025-09-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanrepayback_comment'),
    ]

    operations = [
    ]
