# Generated by Django 5.1.6 on 2025-09-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_remove_loanrequestfee_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequestfee',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
