# Generated by Django 5.1.6 on 2025-08-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanrequest_approved_amount_not_greater_than_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('Fullpaid', 'Fullpaid')], default='pending', max_length=20),
        ),
    ]
