# Generated by Django 5.1.6 on 2025-09-12 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20250910_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 12, 6, 41, 23, 615872, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
