# Generated by Django 5.1.6 on 2025-09-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loanrequestfee_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequestfee',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('used', 'Used for Loan'), ('expired', 'Expired/Closed')], default='paid', max_length=20),
        ),
    ]
