# Generated by Django 5.1.6 on 2026-01-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_target_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
