# Generated by Django 5.1.6 on 2025-10-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pagepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagepermission',
            old_name='page_name',
            new_name='page',
        ),
    ]
