# Generated by Django 5.1.6 on 2025-10-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_total_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
