# Generated by Django 5.1.6 on 2025-09-28 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_total_savings'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dividend_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_dividend_pool', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_distributed', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='accounts.member')),
            ],
        ),
    ]
