# Generated by Django 5.1.6 on 2025-10-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
