# Generated by Django 5.1.6 on 2025-10-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dividend'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='unit_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
