# Generated by Django 5.1.6 on 2025-11-03 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
