# Generated by Django 5.1.6 on 2025-11-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dividend_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
