# Generated by Django 5.1.6 on 2025-11-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_dividend_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DividendHistory',
        ),
    ]
