# Generated by Django 5.1.6 on 2025-11-09 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_page_name_pagepermission_page'),
        ('main', '0007_delete_dividendhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('withdrawn_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('withdrawn_from_loanable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('withdrawn_from_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_loanable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_partial_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_withdrawal_requests', to='accounts.member')),
            ],
            options={
                'verbose_name': 'Partial Withdrawal',
                'verbose_name_plural': 'Partial Withdrawals',
                'ordering': ['-date_requested'],
            },
        ),
    ]
