# Generated by Django 5.1.6 on 2025-11-09 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_page_name_pagepermission_page'),
        ('main', '0008_partialwithdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partialwithdrawal',
            options={'ordering': ['-date_requested']},
        ),
        migrations.RemoveField(
            model_name='partialwithdrawal',
            name='remaining_investment',
        ),
        migrations.RemoveField(
            model_name='partialwithdrawal',
            name='remaining_loanable',
        ),
        migrations.RemoveField(
            model_name='partialwithdrawal',
            name='remaining_savings',
        ),
        migrations.AlterField(
            model_name='partialwithdrawal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partialwithdrawal',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_withdrawals', to='accounts.member'),
        ),
    ]
