# Generated by Django 5.1.6 on 2025-09-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableformfee',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('used', 'Used for Loan'), ('expired', 'Expired/Closed')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='consumabletype',
            name='request_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
