# Generated by Django 5.1.6 on 2025-08-06 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableformfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 6, 12, 54, 43, 187152, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
