# Generated by Django 5.1.6 on 2025-09-12 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybackconsumable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 12, 6, 50, 5, 140658, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
