# Generated by Django 5.1.6 on 2025-10-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablerequest',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
    ]
