# Generated by Django 5.1.6 on 2025-09-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0002_consumableformfee_status_consumabletype_request_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableformfee',
            name='consumable_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consumable.consumabletype'),
            preserve_default=False,
        ),
    ]
