# Generated by Django 5.1.6 on 2025-08-09 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_unit'),
        ('consumable', '0002_consumableformfee_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumableformfee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_fee', to='accounts.member'),
        ),
    ]
