# Generated by Django 5.1.6 on 2025-11-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0002_consumablerequest_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybackconsumable',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts'),
        ),
    ]
