# Generated by Django 5.1.6 on 2025-09-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0003_consumableformfee_consumable_type'),
        ('loan', '0004_loanrequestfee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablerequest',
            name='account_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='bank_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.bankcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='bank_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.bankname'),
            preserve_default=False,
        ),
    ]
