# Generated by Django 5.1.6 on 2025-08-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0003_alter_consumableformfee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumableformfee',
            old_name='user',
            new_name='member',
        ),
    ]
