# Generated by Django 5.1.6 on 2025-09-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0004_consumablerequest_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumablerequest',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='consumablerequest',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='consumablerequest',
            name='bank_name',
        ),
    ]
