# Generated by Django 5.1.6 on 2025-08-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0005_projectfinanceapplication_projectfinancerequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfinancerequest',
            name='amount',
        ),
        migrations.AddField(
            model_name='projectfinancerequest',
            name='markup_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Markup rate as a percentage (e.g., 5.00 for 5%).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='projectfinancerequest',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='The amount requested by the member.', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectfinancerequest',
            name='total_repayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total amount to be repaid, including markup.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='projectfinancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Declined', 'Declined'), ('Completed', 'Completed'), ('FullyPaid', 'Fully Paid')], default='Pending', max_length=20),
        ),
    ]
