# Generated by Django 5.1.6 on 2025-09-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0003_purchaseditemadjustment_sellingplanadjustment'),
        ('consumable', '0005_remove_consumablerequest_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablerequestdetail',
            name='selling_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='PurchasedItems.sellingplan'),
        ),
    ]
