# Generated by Django 5.1.6 on 2025-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0006_remove_projectfinancerequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfinanceapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20),
        ),
    ]
