# Generated by Django 5.1.6 on 2025-09-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0006_alter_consumablerequestdetail_selling_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablerequest',
            name='guest_ippis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
