# Generated by Django 5.1.6 on 2025-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0007_projectfinanceapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
