# Generated by Django 5.1.6 on 2025-08-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0008_item_quantity_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfinanceapplication',
            name='comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
