# Generated by Django 5.1.6 on 2025-09-18 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0008_alter_consumablerequest_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_date', models.DateTimeField(auto_now_add=True)),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_logs', to='consumable.consumablerequestdetail')),
            ],
        ),
    ]
