# Generated by Django 5.1.6 on 2025-09-24 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_total_savings'),
        ('consumable', '0009_pickedlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableformfee',
            name='guest_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consumable.consumablerequest'),
        ),
        migrations.AlterField(
            model_name='consumableformfee',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumable_fee', to='accounts.member'),
        ),
        migrations.AddConstraint(
            model_name='consumableformfee',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False), ('status', 'paid')), fields=('member', 'consumable_type'), name='unique_member_paid_fee'),
        ),
        migrations.AddConstraint(
            model_name='consumableformfee',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_request__isnull', False), ('status', 'paid')), fields=('guest_request', 'consumable_type'), name='unique_guest_paid_fee'),
        ),
    ]
