# Generated by Django 5.1.6 on 2025-08-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0009_projectfinanceapplication_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfinanceapplication',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
