# Generated by Django 5.1.6 on 2025-09-24 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_total_savings'),
        ('consumable', '0010_consumableformfee_guest_request_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consumableformfee',
            name='unique_member_paid_fee',
        ),
        migrations.RemoveConstraint(
            model_name='consumableformfee',
            name='unique_guest_paid_fee',
        ),
        migrations.RemoveField(
            model_name='consumableformfee',
            name='guest_request',
        ),
        migrations.AlterField(
            model_name='consumableformfee',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consumable_fee', to='accounts.member'),
            preserve_default=False,
        ),
    ]
