# Generated by Django 5.1.6 on 2025-08-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0010_alter_projectfinanceapplication_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfinanceapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
