# Generated by Django 5.1.6 on 2025-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0011_remove_consumableformfee_unique_member_paid_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableformfee',
            name='guest_ippis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consumableformfee',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
