# Generated by Django 5.1.6 on 2025-08-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0011_alter_projectfinanceapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfinancerequest',
            name='application',
        ),
        migrations.RemoveField(
            model_name='projectfinancepayment',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='projectfinancepayment',
            name='request',
        ),
        migrations.RemoveField(
            model_name='projectfinancerequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='projectfinancerequest',
            name='guarantor',
        ),
        migrations.DeleteModel(
            name='ProjectFinanceApplication',
        ),
        migrations.DeleteModel(
            name='ProjectFinancePayment',
        ),
        migrations.DeleteModel(
            name='ProjectFinanceRequest',
        ),
    ]
