# Generated by Django 5.1.6 on 2025-08-25 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0002_initial'),
        ('consumable', '0012_remove_projectfinancerequest_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumablerequest',
            name='consumable_type',
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='selling_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consumable_requests', to='PurchasedItems.sellingplan'),
            preserve_default=False,
        ),
    ]
