# Generated by Django 5.1.6 on 2025-09-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_total_savings'),
        ('consumable', '0012_consumableformfee_guest_ippis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumableformfee',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumable_fee', to='accounts.member'),
        ),
    ]
