# Generated by Django 5.1.6 on 2025-08-25 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0002_initial'),
        ('consumable', '0013_remove_consumablerequest_consumable_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablerequest',
            name='selling_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumable_requests', to='PurchasedItems.sellingplan'),
        ),
    ]
