# Generated by Django 5.1.6 on 2025-08-25 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0002_initial'),
        ('consumable', '0014_alter_consumablerequest_selling_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablerequestdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchasedItems.sellingplan'),
        ),
    ]
