# Generated by Django 5.1.6 on 2025-08-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0015_alter_consumablerequestdetail_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumablerequestdetail',
            old_name='item',
            new_name='selling_plan',
        ),
    ]
