# Generated by Django 5.1.6 on 2025-08-25 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0016_rename_item_consumablerequestdetail_selling_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumablerequest',
            name='selling_plan',
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='consumable_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables_type', to='consumable.consumabletype'),
        ),
    ]
