# Generated by Django 5.1.6 on 2025-08-26 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0017_remove_consumablerequest_selling_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumablerequestdetail',
            old_name='selling_plan',
            new_name='selling_item',
        ),
        migrations.AlterField(
            model_name='consumablerequest',
            name='consumable_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumables_type', to='consumable.consumabletype'),
        ),
    ]
