# Generated by Django 5.1.6 on 2025-08-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0018_rename_selling_plan_consumablerequestdetail_selling_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumabletype',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='consumabletype',
            name='max_loan_term_months',
        ),
    ]
