# Generated by Django 5.1.6 on 2025-08-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfinance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfinancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Completed', 'Completed'), ('FullyPaid', 'Fully Paid')], default='Pending', max_length=20),
        ),
    ]
