# Generated by Django 5.1.6 on 2025-08-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfinance', '0002_alter_projectfinancerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfinancepayment',
            name='balance_remaining',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
