# Generated by Django 5.1.6 on 2025-08-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectfinance', '0003_projectfinancepayment_balance_remaining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfinancepayment',
            old_name='paid_at',
            new_name='created_at',
        ),
    ]
