# Generated by Django 5.1.6 on 2025-09-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfinance', '0004_rename_paid_at_projectfinancepayment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfinancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Completed', 'Completed'), ('FullyPaid', 'FullyPaid')], default='Pending', max_length=20),
        ),
    ]
