# Generated by Django 4.2.27 on 2026-05-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guest_ippis', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('ItemPicked', 'ItemPicked'), ('Fully Paid', 'Fully Paid')], default='Pending', max_length=20)),
                ('file_payslip', models.ImageField(blank=True, null=True, upload_to='request_payslips/')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='request_passports/')),
                ('guarantor_accepted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_member_requests', to=settings.AUTH_USER_MODEL)),
                ('guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed', to='accounts.member')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_requests', to='accounts.member')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='brand_images/')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField(help_text='Reason for return (e.g. damaged, overstock)')),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.receiveditem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SellingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('available', models.BooleanField(default=True)),
                ('include_expenditure', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_selling_plans', to=settings.AUTH_USER_MODEL)),
                ('received_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selling_plan', to='inventory_app.receiveditem')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='receiveditem',
            name='stock_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_app.stockin'),
        ),
        migrations.CreateModel(
            name='MemberRequestPayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_date', models.DateField()),
                ('balance_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='member_request_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_request_payments', to=settings.AUTH_USER_MODEL)),
                ('member_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='inventory_app.memberrequest')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('markup_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Markup rate as a percentage (e.g., 5.00 for 5%).', max_digits=5, null=True)),
                ('approved_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_months', models.PositiveIntegerField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_details', to='inventory_app.sellingplan')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory_app.memberrequest')),
            ],
        ),
    ]
