# Generated by Django 4.2.27 on 2026-05-25 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveditem',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 25, 18, 44, 29, 174485, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
