# Generated by Django 4.2.27 on 2026-04-28 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_app', '0004_stockreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('request_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guest_ippis', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Itempicked', 'ItemPicked'), ('FullyPaid', 'Fully Paid')], default='Pending', max_length=20)),
                ('file_payslip', models.ImageField(blank=True, null=True, upload_to='request_payslips/')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='request_passports/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_member_requests', to=settings.AUTH_USER_MODEL)),
                ('batch_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_requests', to='inventory_app.batchtype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Request',
                'verbose_name_plural': 'Member Requests',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='MemberRequestPayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_date', models.DateField()),
                ('balance_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='member_request_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_request_payments', to=settings.AUTH_USER_MODEL)),
                ('member_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='inventory_app.memberrequest')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_quantity', models.PositiveIntegerField(blank=True, help_text='Staff can approve a different quantity than what was requested', null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_details', to='inventory_app.stockitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory_app.memberrequest')),
            ],
        ),
    ]
