# Generated by Django 4.2.27 on 2026-04-29 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_app', '0005_batchtype_memberrequest_memberrequestpayback_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockItem',
            new_name='ReceivedItem',
        ),
        migrations.CreateModel(
            name='SellingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price_per_unit', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=12)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity to sell')),
                ('notes', models.TextField(blank=True, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated profit', max_digits=12, null=True)),
                ('available', models.BooleanField(default=True)),
                ('include_expenditure', models.BooleanField(default=True, help_text='Include purchased item expenditure in cost calculation')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_plan_created_by', to=settings.AUTH_USER_MODEL)),
                ('recevied_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selling_plan', to='inventory_app.receiveditem')),
            ],
            options={
                'verbose_name': 'Selling Plan',
                'verbose_name_plural': 'Selling Plans',
                'ordering': ['-date_created'],
            },
        ),
    ]
