# Generated by Django 4.2.27 on 2026-04-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_rename_stockitem_receiveditem_sellingplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingplan',
            old_name='recevied_item',
            new_name='received_item',
        ),
    ]
