# Generated by Django 4.2.27 on 2026-04-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0007_rename_recevied_item_sellingplan_received_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingplan',
            old_name='received_item',
            new_name='recevied_item',
        ),
    ]
