# Generated by Django 4.2.27 on 2026-04-29 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_app', '0008_rename_received_item_sellingplan_recevied_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingplan',
            old_name='recevied_item',
            new_name='received_item',
        ),
        migrations.AlterField(
            model_name='sellingplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_selling_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellingplan',
            name='include_expenditure',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sellingplan',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sellingplan',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellingplan',
            name='selling_price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
