# Generated by Django 4.2.27 on 2026-04-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0009_rename_recevied_item_sellingplan_received_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellingplan',
            options={'ordering': ['-date_created']},
        ),
    ]
