# Generated by Django 4.2.27 on 2026-04-29 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0010_alter_sellingplan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberrequest',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='memberrequest',
            name='batch_type',
        ),
        migrations.AddField(
            model_name='memberrequest',
            name='gaurantor_ippis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('ItemPicked', 'ItemPicked'), ('Fully Paid', 'Fully Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberrequestdetail',
            name='approved_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberrequestdetail',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='request_details', to='inventory_app.receiveditem'),
            preserve_default=False,
        ),
    ]
