# Generated by Django 4.2.27 on 2026-04-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0011_alter_memberrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveditem',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_images/'),
        ),
    ]
