# Generated by Django 4.2.27 on 2026-05-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0014_alter_memberrequestdetail_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrequestdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_details', to='inventory_app.sellingplan'),
        ),
    ]
