# Generated by Django 4.2.27 on 2026-05-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0015_alter_memberrequestdetail_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchType',
        ),
    ]
