# Generated by Django 5.1.6 on 2026-01-04 07:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumablePurchasedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('amount_requested', models.DecimalField(decimal_places=2, help_text='Amount requested for purchase', max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by admin', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('accounted', 'Fully Accounted')], default='pending', max_length=20)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consumable Purchase Request',
                'verbose_name_plural': 'Consumable Purchase Requests',
                'ordering': ['-date_requested'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Item description')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12)),
                ('receipt', models.FileField(blank=True, help_text='Upload receipt image', null=True, upload_to='receipts/%Y/%m/')),
                ('expenditure_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional expenditure (transport, etc.)', max_digits=12)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Purchased Item',
                'verbose_name_plural': 'Purchased Items',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedItemAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date_adjusted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Purchased Item Adjustment',
                'verbose_name_plural': 'Purchased Item Adjustments',
                'ordering': ['-date_adjusted'],
            },
        ),
        migrations.CreateModel(
            name='SellingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price_per_unit', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=12)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity to sell')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated profit', max_digits=12, null=True)),
                ('available', models.BooleanField(default=True)),
                ('include_expenditure', models.BooleanField(default=True, help_text='Include purchased item expenditure in cost calculation')),
            ],
            options={
                'verbose_name': 'Selling Plan',
                'verbose_name_plural': 'Selling Plans',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SellingPlanAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date_adjusted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Selling Plan Adjustment',
                'verbose_name_plural': 'Selling Plan Adjustments',
                'ordering': ['-date_adjusted'],
            },
        ),
    ]
