# Generated by Django 5.1.6 on 2025-07-21 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PurchasedItems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablepurchasedrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumablepurchasedrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseditem',
            name='consumable_purchased_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='PurchasedItems.consumablepurchasedrequest'),
        ),
        migrations.AddField(
            model_name='sellingplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellingplan',
            name='purchased_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selling_plan', to='PurchasedItems.purchaseditem'),
        ),
    ]
