# Generated by Django 5.1.6 on 2025-08-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingplan',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
