# Generated by Django 5.1.6 on 2025-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0003_purchaseditem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablepurchasedrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('accounted', 'Fully Accounted')], default='pending', max_length=20),
        ),
    ]
