# Generated by Django 5.1.6 on 2025-09-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0003_purchaseditemadjustment_sellingplanadjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingplan',
            name='description',
        ),
    ]
