# Generated by Django 5.1.6 on 2025-08-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0003_sellingplan_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
