# Generated by Django 5.1.6 on 2025-10-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0004_alter_consumablepurchasedrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablepurchasedrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
