# Generated by Django 5.1.6 on 2025-08-25 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0004_purchaseditem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseditem',
            old_name='description',
            new_name='description_title',
        ),
        migrations.AddField(
            model_name='sellingplan',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PurchasedItems.purchaseditem'),
        ),
    ]
