# Generated by Django 5.1.6 on 2025-08-26 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0005_rename_description_purchaseditem_description_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingplan',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PurchasedItems.purchaseditem'),
        ),
    ]
