# Generated by Django 5.1.6 on 2025-09-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0005_alter_consumablepurchasedrequest_amount_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingplan',
            name='include_expenditure',
            field=models.BooleanField(default=True, help_text='If True, include purchased_item.expenditure_amount (spread across units) when computing purchase cost.'),
        ),
    ]
