# Generated by Django 5.1.6 on 2025-09-21 13:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasedItems', '0006_sellingplan_include_expenditure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumablepurchasedrequest',
            options={'ordering': ['-date_requested'], 'verbose_name': 'Consumable Purchase Request', 'verbose_name_plural': 'Consumable Purchase Requests'},
        ),
        migrations.AlterModelOptions(
            name='purchaseditem',
            options={'ordering': ['-date_added'], 'verbose_name': 'Purchased Item', 'verbose_name_plural': 'Purchased Items'},
        ),
        migrations.AlterModelOptions(
            name='purchaseditemadjustment',
            options={'ordering': ['-date_adjusted'], 'verbose_name': 'Purchased Item Adjustment', 'verbose_name_plural': 'Purchased Item Adjustments'},
        ),
        migrations.AlterModelOptions(
            name='sellingplan',
            options={'ordering': ['-date_created'], 'verbose_name': 'Selling Plan', 'verbose_name_plural': 'Selling Plans'},
        ),
        migrations.AlterModelOptions(
            name='sellingplanadjustment',
            options={'ordering': ['-date_adjusted'], 'verbose_name': 'Selling Plan Adjustment', 'verbose_name_plural': 'Selling Plan Adjustments'},
        ),
        migrations.RemoveField(
            model_name='purchaseditem',
            name='description_title',
        ),
        migrations.AddField(
            model_name='purchaseditem',
            name='description',
            field=models.TextField(default=1, help_text='Item description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumablepurchasedrequest',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, help_text='Amount requested for purchase', max_digits=12),
        ),
        migrations.AlterField(
            model_name='consumablepurchasedrequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by admin', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='consumablepurchasedrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='expenditure_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional expenditure (transport, etc.)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='receipt',
            field=models.FileField(blank=True, help_text='Upload receipt image', null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sellingplan',
            name='include_expenditure',
            field=models.BooleanField(default=True, help_text='Include purchased item expenditure in cost calculation'),
        ),
        migrations.AlterField(
            model_name='sellingplan',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated profit', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sellingplan',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity to sell'),
        ),
        migrations.AlterField(
            model_name='sellingplan',
            name='selling_price_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=12),
        ),
    ]
