# Generated by Django 5.1.6 on 2026-01-04 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsavingstergetsavingsrequestform',
            name='savings_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special_savings.savingtype'),
        ),
    ]
