# Generated by Django 5.1.6 on 2026-01-05 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('special_savings', '0002_alter_specialsavingstergetsavingsrequestform_savings_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialsavingstergetsavingsrequestform',
            name='duration_in_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TargetSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True)),
                ('month_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_savings', to='accounts.member')),
            ],
            options={
                'indexes': [models.Index(fields=['member', 'month'], name='special_sav_member__ca88ad_idx')],
                'unique_together': {('member', 'month')},
            },
        ),
    ]
