# Generated by Django 4.2.27 on 2026-04-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_savings', '0003_specialsavingswithdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingtype',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
