# Generated by Django 4.2.27 on 2026-06-12 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_app', '0002_ramrequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts'),
        ),
        migrations.AddField(
            model_name='payment',
            name='repayment_mounth',
            field=models.DateField(default=datetime.datetime(2026, 6, 12, 15, 31, 42, 594881, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
