# Generated by Django 4.2.27 on 2026-06-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ram_app', '0003_payment_payment_receipt_payment_repayment_mounth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramrequest',
            name='file_payslip',
            field=models.ImageField(blank=True, null=True, upload_to='request_payslips/'),
        ),
        migrations.AddField(
            model_name='ramrequest',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram_guaranteed', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='ramrequest',
            name='guarantor_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ramrequest',
            name='guest_ippis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ramrequest',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ramrequest',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ramrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('fully Paid', 'Fully Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
