# Generated by Django 4.2.27 on 2026-06-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_app', '0004_ramrequest_file_payslip_ramrequest_guarantor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
