# Generated by Django 4.2.27 on 2026-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_app', '0005_sellingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramrequestdetails',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
