# Generated by Django 4.2.27 on 2026-06-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ram_app', '0006_ramrequestdetails_duration_months'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellingPlan',
            new_name='Markup',
        ),
    ]
